### ISSUE TITLE
Inline validation raises plone.transformchain Unexpected error

### ISSUE THREAD

**Issue by oggers** [plone/plone4.csrffixes#9]
Hi,

I have just installed this patch product and I get the following error every time a form tries to do inline validation through ajax.
```
2015-10-08 21:04:42 ERROR plone.transformchain Unexpected error whilst trying to apply transform chain
Traceback (most recent call last):
  File "/home/oggers/Proyectos/Apanymantel/Plone-4.3/buildout-cache/eggs/plone.transformchain-1.0.4-py2.7.egg/plone/transformchain/transformer.py", line 48, in __call__
    newResult = handler.transformIterable(result, encoding)
  File "/home/oggers/Proyectos/Apanymantel/Plone-4.3/buildout-cache/eggs/plone4.csrffixes-1.0.4-py2.7.egg/plone4/csrffixes/transform.py", line 77, in transformIterable
    tool = getToolByName(context, 'portal_url', None)
  File "<string>", line 14, in check_getToolByName
TypeError: Object found is not a portal tool (portal_url)
```

At the time the error raises (clues)
- context -> Products.Five.metaclass.CheckoutForm
- self.request['PUBLISHED'] -> Products.Five.metaclass.InlineValidationView

**Comment by vangheem** [comment]
Yikes. I'm surprised that would through a TypeError instead of just returning None. I'll put out a fix asap.

**Comment by vangheem** [comment]
https://github.com/plone/plone4.csrffixes/commit/0dfac97851b80efbabb5abde290f52995ae4c0b8 and https://github.com/plone/plone.protect/commit/a11a94b3475584e12f6daa3b5d118f0b570278a1 fixes it.

Would you might testing plone4.csrffixes 1.0.5 and plone.protect 3.0.14 please?

**Comment by oggers** [comment]
Just upgraded and tested, no more errors.

Thank you, for your support.
